export const FIXTURE_CURRENT_COMPANY = {
  'data': {
    'id': 1,
    'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
    'created_at': '2019-07-10 15:34:30',
    'status': 1,
    'name': 'FreshBus',
    'address': '1832 Test Ave',
    'address2': 'unit 10',
    'city': 'Chicago',
    'state': 'IL',
    'zip': '60606',
    'country': 'US',
    'website': null,
    'notes': null,
    'members': [
      {
        'id': 1,
        'uuid': '4314a914-b8d8-4ad8-b3cf-a3ece1a4dd88',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 1,
        'level_name': 'Platform Admin',
        'first_name': 'Demo',
        'last_name': 'Admin',
        'name': 'Demo Admin',
        'email': 'demoAdmin@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '2019-07-11 20:44:08',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      {
        'id': 2,
        'uuid': 'd5f4102a-f31b-4426-8862-9d238adcdc57',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 1,
        'level_name': 'Platform Admin',
        'first_name': 'Level 1',
        'last_name': 'User',
        'name': 'Level 1 User',
        'email': 'level1@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      {
        'id': 3,
        'uuid': '3546ddce-d736-4410-a6a9-1ca60597b425',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 2,
        'level_name': 'Platform Director',
        'first_name': 'Level 2',
        'last_name': 'User',
        'name': 'Level 2 User',
        'email': 'level2@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      { 'id': 4,
        'uuid': '79a0a719-080c-4762-a0cd-ace9af9c1bf7',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 3,
        'level_name': 'Platform Lead',
        'first_name': 'Level 3',
        'last_name': 'User',
        'name': 'Level 3 User',
        'email': 'level3@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      {
        'id': 5,
        'uuid': 'da25b4cd-8dc6-4b7c-8d79-083a0939f130',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 4,
        'level_name': 'Platform Member',
        'first_name': 'Level 4',
        'last_name': 'User',
        'name': 'Level 4 User',
        'email': 'level4@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      {
        'id': 6,
        'uuid': 'ac64f94f-b58e-436d-8126-72a13d487d17',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 5,
        'level_name': 'Company Admin',
        'first_name': 'Level 5',
        'last_name': 'User',
        'name': 'Level 5 User',
        'email': 'level5@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:30',
        'industry_roles': []
      },
      {
        'id': 7,
        'uuid': '8a1c6bee-6cc2-4bfe-bbfd-b9878c1fb7d1',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 6,
        'level_name': 'Company Director',
        'first_name': 'Level 6',
        'last_name': 'User',
        'name': 'Level 6 User',
        'email': 'level6@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': []
      },
      {
        'id': 8,
        'uuid': '95ca3e05-bba1-431d-adc3-2a954e9be7f9',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 7,
        'level_name': 'Company Lead',
        'first_name': 'Level 7',
        'last_name': 'User',
        'name': 'Level 7 User',
        'email': 'level7@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': []
      },
      {
        'id': 10,
        'uuid': 'c0f68ef9-cdf3-4719-9ed0-4dfdc23d4045',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 1,
        'level_name': 'Platform Admin',
        'first_name': 'Colleague 1',
        'last_name': 'User',
        'name': 'Colleague 1 User',
        'email': 'colleague1@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': {
          'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': []
        },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': []
      },
      {
        'id': 11,
        'uuid': '88ab02fc-0785-4342-8fb1-056fa57b177c',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 2,
        'level_name': 'Platform Director',
        'first_name': 'Colleague 2',
        'last_name': 'User',
        'name': 'Colleague 2 User',
        'email': 'colleague2@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': [] },
      { 'id': 12,
        'uuid': '7c0bf87f-6ef5-454d-aee1-f408ea4518b6',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 3,
        'level_name': 'Platform Lead',
        'first_name': 'Colleague 3',
        'last_name': 'User',
        'name': 'Colleague 3 User',
        'email': 'colleague3@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': [] },
      { 'id': 13,
        'uuid': '27fc1499-6b9a-42da-a437-e74761bce3cc',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 4,
        'level_name': 'Platform Member',
        'first_name': 'Colleague 4',
        'last_name': 'User',
        'name': 'Colleague 4 User',
        'email': 'colleague4@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': true,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': [] },
      { 'id': 14,
        'uuid': 'ed14ae68-b6a6-4b78-b7c0-4a1069fd286a',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 5,
        'level_name': 'Company Admin',
        'first_name': 'Colleague 5',
        'last_name': 'User',
        'name': 'Colleague 5 User',
        'email': 'colleague5@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:32',
        'industry_roles': [] },
      { 'id': 15,
        'uuid': 'f2b36beb-a3e1-4d03-9647-4e74ee801e6f',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 6,
        'level_name': 'Company Director',
        'first_name': 'Colleague 6',
        'last_name': 'User',
        'name': 'Colleague 6 User',
        'email': 'colleague6@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:33',
        'industry_roles': [] },
      { 'id': 16,
        'uuid': 'da009be1-00f3-4a58-bf18-f4a3af308ca6',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 7,
        'level_name': 'Company Lead',
        'first_name': 'Colleague 7',
        'last_name': 'User',
        'name': 'Colleague 7 User',
        'email': 'colleague7@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:33',
        'industry_roles': [] },
      { 'id': 17,
        'uuid': '21af0be6-5215-4c89-836a-4e649c6dbfcf',
        'company_id': 1,
        'company_name': 'FreshBus',
        'status': 1,
        'type': 1,
        'level': 8,
        'level_name': 'Company Member',
        'first_name': 'Colleague 8',
        'last_name': 'User',
        'name': 'Colleague 8 User',
        'email': 'colleague8@example.com',
        'mobile_phone': '321-123-1234',
        'office_phone': '123-456-7890',
        'notes': null,
        'title': null,
        'avatar': 'https://via.placeholder.com/800x600.png',
        'requested_company': null,
        'company': { 'id': 1,
          'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
          'created_at': '2019-07-10 15:34:30',
          'status': 1,
          'name': 'FreshBus',
          'address': '1832 Test Ave',
          'address2': 'unit 10',
          'city': 'Chicago',
          'state': 'IL',
          'zip': '60606',
          'country': 'US',
          'website': null,
          'notes': null,
          'members_count': null,
          'teams_count': null,
          'tags': [],
          'logo': 'https://via.placeholder.com/800x600.png',
          'company_types': [] },
        'last_login': '',
        'has_admin_access': false,
        'joined_at': '2019-07-10 15:34:33',
        'industry_roles': [] }],
    'members_count': 16,
    'teams_count': 2,
    'tags': [],
    'logo': 'https://via.placeholder.com/800x600.png',
    'admin': { 'id': 1,
      'uuid': '4314a914-b8d8-4ad8-b3cf-a3ece1a4dd88',
      'company_id': 1,
      'company_name': 'FreshBus',
      'status': 1,
      'type': 1,
      'level': 1,
      'level_name': 'Platform Admin',
      'first_name': 'Demo',
      'last_name': 'Admin',
      'name': 'Demo Admin',
      'email': 'demoAdmin@example.com',
      'mobile_phone': '321-123-1234',
      'office_phone': '123-456-7890',
      'notes': null,
      'title': null,
      'avatar': 'https://via.placeholder.com/800x600.png',
      'requested_company': null,
      'company': { 'id': 1,
        'uuid': 'deae5b25-60ad-4ff4-b01b-05558f7aec33',
        'created_at': '2019-07-10 15:34:30',
        'status': 1,
        'name': 'FreshBus',
        'address': '1832 Test Ave',
        'address2': 'unit 10',
        'city': 'Chicago',
        'state': 'IL',
        'zip': '60606',
        'country': 'US',
        'website': null,
        'notes': null,
        'members_count': null,
        'teams_count': null,
        'tags': [],
        'logo': 'https://via.placeholder.com/800x600.png',
        'company_types': []
      },
      'last_login': '2019-07-11 20:44:08',
      'has_admin_access': true,
      'joined_at': '2019-07-10 15:34:30',
      'industry_roles': []
    },
    'company_types': []
  },
  'meta': {
    'types': [
      { 'id': 1,
        'name': 'Registered Representative'
      },
      { 'id': 2,
        'name': 'RIA'
      },
      {
        'id': 3,
        'name': 'Broker Dealer'
      },
      {
        'id': 4,
        'name': 'Managing Broker Dealer (With retail Business)'
      },
      {
        'id': 5,
        'name': 'Managing Broker Dealer (Without retail Business)'
      },
      {
        'id': 6,
        'name': 'Product Sponsor'
      },
      {
        'id': 7,
        'name': 'Family Office'
      },
      {
        'id': 8,
        'name': 'Other'
      }
    ],
    'statuses': [
      {
        'id': 1,
        'name': 'ACTIVE'
      },
      {
        'id': 2,
        'name': 'INACTIVE'
      },
      {
        'id': 3,
        'name': 'HOLD'
      },
      {
        'id': 4,
        'name': 'PENDING'
      },
      {
        'id': 5,
        'name': 'DENIED'
      }
    ]
  }
}
